### ISSUE TITLE
Block history squares and x-axis are unaligned

### ISSUE THREAD

**Issue by echa** [blockwatch-cc/tzstats#12]
**Describe the bug**
On my screen (Mac Retina 1,680 × 1,050) the alignment between block history squares and the timeline axis is off. The chain of squares ends somewhere at 75% width of the axis. Also timestamp labels run backwards in time (left is earlier than right)

**To Reproduce**
1. Go to https://alpha.tzstats.com/block/BMc7TLD3VsxnjWL4mc2fAga3ALvaLr48HzwusHcqLNuo9gJCQXH
2. Look closely at block history axis and chain of blocks

**Expected behavior**
Time labels should be increasing from left to right. Chain of squares and time axis should be aligned.

**Screenshots**
<img width="1121" alt="Screen Shot 2019-07-31 at 11 49 57 AM" src="https://user-images.githubusercontent.com/910436/62202866-656cd200-b38a-11e9-8e2c-5b6146e1f72b.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 68

**Comment by andyvauliln** [comment]
fixed
