### ISSUE TITLE
App overscrolls on small size screen

### ISSUE THREAD

**Issue by bitcoinbender** [blockwatch-cc/tzstats#13]
**Describe the bug**
App overscrolls the bottom on small screen.
If i increase Browser Zoom further the overscroll gets bigger accordingly.

**To Reproduce**
1. Go to https://alpha.tzstats.com/ in Browser
2. Browser Zoom into the app
3. Scroll down to very bottom

**Screenshots**
![Capture](https://user-images.githubusercontent.com/39401217/62203339-3dca3980-b38b-11e9-8f05-0cae019429da.JPG)
Look closely at the bottom

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
Increase App Canvas Size, according to the size of the sidebar

**Comment by echa** [comment]
A half-way solution could be to add `min-height: 100vh` and remove `height: 100%` at `html`, `body`, `#root`, and the outer layout wrapper div. However, this seems to break infinite scroll for block and account lists.

**Comment by andyvauliln** [comment]
possible fixed, check it please
