### ISSUE TITLE
Market screen data is off

### ISSUE THREAD

**Issue by echa** [blockwatch-cc/tzstats#19]
**Describe the bug**
Exchange volume data on the market screen seems to display only a single market for each exchange. E.g. Kraken has 4.35 Mill tz traded in last 24h but we show only 1.6 M which is the number for Kraken XTZ_USD volume alone.

**To Reproduce**
1. Go to https://alpha.tzstats.com/market
2. See 'Volumes by Exchanges'

**Expected behavior**
Volume numbers should reflect all pairs traded on an exchange. To do that sum up the `volume_base` field across all XTZ_* markets per exchange. Be flexible in the number of exhanges and markets as the backend may add more.

The reference screenshot below is taken from Blockwatch backend which shows correct volumes.

**Screenshots**
<img width="552" alt="Screen Shot 2019-07-31 at 1 22 36 PM" src="https://user-images.githubusercontent.com/910436/62208897-61e04780-b398-11e9-8153-401e84a91aaf.png">
<img width="467" alt="Screen Shot 2019-07-31 at 1 36 14 PM" src="https://user-images.githubusercontent.com/910436/62208898-61e04780-b398-11e9-9763-9c967fff2a2f.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 68

**Comment by andyvauliln** [comment]
Wizard!)
