### ISSUE TITLE
Landing: Staking Activity

### ISSUE THREAD

**Issue by echa** [blockwatch-cc/tzstats#25]
Still called "Tezos supply" in the design, but that's wrong.

1. Rename card title to "Staking Activity"
2. Calculate correct numbers (see below)
3. Change number font to smaller size (14px) matching the font size next to graphs

The data is available at `/explorer/chain` and the mapping is as follows:
```
Design            Unit   Struct Field or Formula
--------------------------------------------------------
Staking Ratio     %      supply.staking*100/supply.total
Active Bakers     -      delegates
Inflation         %      inflation_rate_1y
Staking Reward    %      inflation_rate_1y / (supply.staking / supply.total)
```

**Comment by andyvauliln** [comment]
implemented,  please check
