### ISSUE TITLE
Landing: Price & Volume Charts

### ISSUE THREAD

**Issue by echa** [blockwatch-cc/tzstats#26]
1. Increase graph height to show more action
2. Place numbers that are currently under the graphs on the right side in vertical layout
    2.1 Labels and Order for Price History:
        - Open Price
        - Close Price
        - Highest Price
        - Lowest Price
    2.2 Labels and Order for On-Chain Volume
        - 24h Transactions
        - 24h Volume
        - 30d Avergae Transactions
        - 30d Average Volume
3. Snap X and Y to graph point
<img width="565" alt="Screen Shot 2019-08-12 at 12 14 00 PM" src="https://user-images.githubusercontent.com/910436/62864062-03598880-bd0b-11e9-978b-b6e85a358f8d.png">

4. Format dates as `Mon, Aug 05`
5. Replace current horizontal dashed min/max lines with 3 equi-distant horizontal grid lines (solid white 30% transparency) and show their value at right side
6. Background color for cards has changed in design, see Invision
7. Replace gradient used to fill graph areas with solid 20% transparent color (base color is same as graph color)

**Comment by andyvauliln** [comment]
fixed,  please check
