### ISSUE TITLE
Election: Missing links and style issues

### ISSUE THREAD

**Issue by echa** [blockwatch-cc/tzstats#29]
To finalize our election screen, there's only a few tiny problems left:

1. From Proposal Name link to Blog Post
2. From Proposal Hash link to Source Archive
3. From Proposal Source link to Account
4. Add Blocy Icon to account
5. Right align Start/End Block text
6. Make Quorum a 2-line entry like participation (both on stage 2 and 4)
7. Do not show Nay graph section when zero
8. Replace sad smiley with a neutral UTF8 character or an embedded SVG icon
9. On empty elections (no proposal was submitted) change step 1 title to 'No proposal submitted'

<img width="980" alt="Screen Shot 2019-08-12 at 3 01 53 PM" src="https://user-images.githubusercontent.com/910436/62872422-bf23b380-bd1d-11e9-97fe-e1f75c265368.png">

**Comment by andyvauliln** [comment]
fixed, please check
