### ISSUE TITLE
Landing: Search field lacks error handling

### ISSUE THREAD

**Issue by echa** [blockwatch-cc/tzstats#30]
For successful searches where an account, block or operation exists, the search functionalty works. Any kind of error breaks it though (seems there is no error handling in place at all):

1. stores data when fetch failed, e.g. for block 5000000
2. does not display error message when fetch fails for an address/block/election/cycle
3. goes to block screen and shows spinner when searching for non existing block height
4. does not translate account names to addresses
5. does not show auto-suggestion when searching for account names
6. goes to account screen and shows spinner when searching for non existing account
7. does not search for protocol proposals (e.g. Babylon)
8. mistakenly detects "Babylon" as block hash (because of prefix B)

**Comment by andyvauliln** [comment]
for the correct handling error messages, i need 404 status code from api, another one points already implemented
