### ISSUE TITLE
Improve the staking capacity calculation

### ISSUE THREAD

**Issue by dansan566** [blockwatch-cc/tzstats#46]
**Is your feature request related to a problem? Please describe.**
It is very harmful to bakers if they exceed their capacity limit. P2P Validator has recently published an article that aims to establish a single approach for available staking capacity calculation and eliminate errors and confusion for end-users on various analytical resources. 

Source: https://economy.p2p.org/confusion-with-calculation-of-available-staking-capacity-in-tezos-who-is-right/

**Describe the solution you'd like**
**Use the following solution:**
```
const CYCLE_LENGTH = 4096
const ENDORSEMENTS_PER_BLOCK = 32
const SECURITY_DEPOSIT_BAKE = 512
const SECURITY_DEPOSIT_ENDORSEMENT = 64
const PRESERVED_CYCLES = 5
```
`SELF_BOND_REQUIREMENT = ((SECURITY_DEPOSIT_BAKE + SECURITY_DEPOSIT_ENDORSEMENT * ENDORSEMENTS_PER_BLOCK) * CYCLE_LENGTH * (PRESERVED_CYCLES+1)) / total_supply`

where total_supply is derived from your API:
https://tzstats.com/docs/api/index.html#supply-table

**Then use:**
`Total Balance / (SELF_BOND_REQUIREMENT / Staking Ratio)`
where Total Balance is the Total (Self Bond) Balance of the Baker

**Comment by echa** [comment]
Awesome! Exactly what I was looking for. A formula based entirely on on-chain data. No magic numbers. The only thing you need to account for is that a baker's total balance does not yet include frozen rewards (not fees). The protocol only counts rewards towards staking once unfrozen. That would mean the total supply should be adjusted down by all pending rewards.

See https://staging.tzstats.com for a version that uses the new formula including the down-adjustment for total supply.

**Comment by echa** [comment]
One more thing: Only staking supply of active delegates counts. Right now there is 21.6M inactive staking supply that does not generate rights, see https://api.tzstats.com/explorer/tip. I updated the staging implementation to use active staking supply only.

Comparing our old formula to yours yields almost identical results. The structure was already the same, but there was a bug that accounted for one cycle less. After applying the fix to use `(PRESERVED_CYCLES+1)` instead of only `PRESERVED_CYCLES` numbers look like this:

```
# Yours for P2P Validator
14,758,294

# Ours for P2P Validator
14,722,671
```

**Comment by dansan566** [comment]
Is this our final solution? I've used tzstats API terms now:

```
const blocks_per_cycle = 4096
const endorsers_per_block = 32
const block_security_deposit = 512
const endorsement_security_deposit = 64
const preserved_cycles = 5
```
`self_bond_requirement = ((block_security_deposit + endorsement_security_deposit * endorsers_per_block) * blocks_per_cycle * (preserved_cycles+1)) / active_staking`

`total_balance/self_bond_requirement`

**Comment by dansan566** [comment]
After talking to some community members (i.e. Baking Bad) I've came to the conclusion that we should use actual rolls:

```
const blocks_per_cycle = 4096
const endorsers_per_block = 32
const block_security_deposit = 512
const endorsement_security_deposit = 64
const preserved_cycles = 5
```
`deposit := (Rolls Owned / Rolls) * blocks_per_cycle * (block_security_deposit + endorsement_security_deposit * endorsers_per_block)`

`maxStakingBalance := Total Balance / (deposit * (preserved_cycles+1)) * Staking Balance`

Example for StakeNow

`deposit = (284 / 74678) * 4096 * (512 + 64 * 32) = 39877.28`
`maxStakingBalance = 278,457.29 / (39877.28 * (5+1)) * 2,278,870 = 2,652,170`

It is very close to your current value.

**Comment by echa** [comment]
Has been fixed a while ago, closing now.
